name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Setup Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Run custom prerender script
        run: |
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
          PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
          node scripts/prerender.js

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}